apiVersion : v1
kind : Service
metadata :
  name : my-service
  labels : 
    app: tomcat-app
spec:
  selector:
    app: tomcat-app
  type : NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 31000

